### Post 추가
POST {{host_api}}/community/v1/post?accountId=USER222
X-Community-Api-Key: {{api_key}}
Content-Type: application/json

{
      "postGroup": "BOSS_NEWS",
      "title": "오늘은 휴일입니다",
      "content": "정기적인 휴일입니다.",
      "workspaceId": "1",
      "sections": [
       {
          "sectionType": "IMAGE",
          "priority": "2",
          "url": "image.jpg",
          "width": "300",
          "height": "400"
       }
      ]
}



### Post 조회
GET {{host_api}}/community/v1/posts?size=3&workspaceId=1&accountId=USER222
X-Community-Api-Key: {{api_key}}
Content-Type: application/json


